# Generated by Django 4.2.30 on 2026-05-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_mfa_enabled_profile_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mfa_backup_codes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
