# Generated by Django 4.2.30 on 2026-06-08 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_webauthn_enabled_webauthncredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="password_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
