# Generated by Django 4.2.30 on 2026-07-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
