services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: securedocs_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    # Wymagane dla Docker wewnatrz nieprivilegowanego kontenera LXC na Proxmox
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: securedocs_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Wymagane dla Docker wewnatrz nieprivilegowanego kontenera LXC na Proxmox
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    depends_on:
      - backend
    restart: always
