# Generated by Django 4.2.30 on 2026-06-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_encrypted",
            field=models.BooleanField(default=False),
        ),
    ]
