# Generated by Django 4.2.30 on 2026-05-26 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Logowanie"),
                            ("VIEW_LIST", "Pobranie listy dokumentów"),
                            ("VIEW_DOCUMENT", "Wyświetlenie dokumentu"),
                            ("DOWNLOAD_DOCUMENT", "Pobranie dokumentu"),
                            ("CREATE_DOCUMENT", "Dodanie dokumentu"),
                            ("UPDATE_DOCUMENT", "Edycja dokumentu"),
                            ("DELETE_DOCUMENT", "Usunięcie dokumentu"),
                            ("ACCESS_DENIED", "Odmowa dostępu"),
                        ],
                        max_length=50,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
