# Generated by Django 4.2.30 on 2026-05-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="entry_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="prev_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
