# Generated by Django 4.2.30 on 2026-06-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_accesslog_entry_hash_accesslog_prev_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Logowanie"),
                    ("VIEW_LIST", "Pobranie listy dokumentów"),
                    ("VIEW_DOCUMENT", "Wyświetlenie dokumentu"),
                    ("DOWNLOAD_DOCUMENT", "Pobranie dokumentu"),
                    ("CREATE_DOCUMENT", "Dodanie dokumentu"),
                    ("UPDATE_DOCUMENT", "Edycja dokumentu"),
                    ("DELETE_DOCUMENT", "Usunięcie dokumentu"),
                    ("ACCESS_DENIED", "Odmowa dostępu"),
                    ("USER_CREATE", "Utworzenie użytkownika"),
                    ("USER_ROLE_CHANGE", "Zmiana roli użytkownika"),
                    ("USER_DEPARTMENT_CHANGE", "Zmiana działu użytkownika"),
                    ("USER_ACTIVATE", "Aktywacja użytkownika"),
                    ("USER_DEACTIVATE", "Dezaktywacja użytkownika"),
                    ("USER_RESET_MFA", "Reset MFA użytkownika"),
                ],
                max_length=50,
            ),
        ),
    ]
