# Generated by Django 4.2.30 on 2026-07-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_accesslog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Logowanie'), ('VIEW_LIST', 'Pobranie listy dokumentów'), ('VIEW_DOCUMENT', 'Wyświetlenie dokumentu'), ('DOWNLOAD_DOCUMENT', 'Pobranie dokumentu'), ('CREATE_DOCUMENT', 'Dodanie dokumentu'), ('UPDATE_DOCUMENT', 'Edycja dokumentu'), ('DELETE_DOCUMENT', 'Usunięcie dokumentu'), ('ACCESS_DENIED', 'Odmowa dostępu'), ('USER_CREATE', 'Utworzenie użytkownika'), ('USER_ROLE_CHANGE', 'Zmiana roli użytkownika'), ('USER_DEPARTMENT_CHANGE', 'Zmiana działu użytkownika'), ('USER_ACTIVATE', 'Aktywacja użytkownika'), ('USER_DEACTIVATE', 'Dezaktywacja użytkownika'), ('USER_RESET_MFA', 'Reset MFA użytkownika'), ('DLP_ALERT', 'Incydent DLP')], max_length=50),
        ),
    ]
